# -*- coding: utf-8 -*-
"""Phase-1 DDXPlus baseline metrics.

Supports JSON or CSV outputs generated by baselines/run_b*.py.
"""

from __future__ import annotations

import argparse
import csv
import glob
import json
import os
import sys
from collections import defaultdict
from typing import Any, Dict, Iterable, List

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass


def _norm(value: Any) -> str:
    return str(value or "").replace("_", " ").replace("-", " ").strip().lower()


def _load_result(path: str) -> List[Dict[str, Any]]:
    if path.lower().endswith(".json"):
        with open(path, "r", encoding="utf-8") as f:
            obj = json.load(f)
        return obj if isinstance(obj, list) else [obj]
    if path.lower().endswith(".csv"):
        with open(path, "r", encoding="utf-8-sig", newline="") as f:
            return list(csv.DictReader(f))
    return []


def load_results(paths: Iterable[str]) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    for pattern in paths:
        for path in glob.glob(pattern):
            rows.extend(_load_result(path))
    return rows


def _hit(pred: Any, truth: Any) -> int:
    pred_n = _norm(pred)
    truth_n = _norm(truth)
    if not truth_n:
        return 0
    return int(truth_n == pred_n or truth_n in pred_n or pred_n in truth_n)


def compute_metrics(rows: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    grouped: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
    for row in rows:
        grouped[str(row.get("mode") or "UNKNOWN")].append(row)

    table = []
    for mode, items in sorted(grouped.items()):
        total = len(items)
        if total == 0:
            continue
        l1 = sum(_hit(r.get("l1_pred"), r.get("l1_truth")) for r in items)
        l2 = sum(_hit(r.get("l2_pred"), r.get("l2_truth")) for r in items)
        l3 = sum(_hit(r.get("l3_pred") or r.get("prediction"), r.get("l3_truth") or r.get("ground_truth")) for r in items)
        top3 = 0
        for row in items:
            truth = _norm(row.get("ground_truth") or row.get("l3_truth"))
            if not truth:
                continue
            retrieved = row.get("retrieved_cases", [])
            if isinstance(retrieved, str):
                try:
                    retrieved = json.loads(retrieved)
                except Exception:
                    retrieved = []
            diagnoses = [_norm(x.get("diagnosis", "")) for x in retrieved[:3] if isinstance(x, dict)]
            top3 += int(any(truth and (truth == d or truth in d or d in truth) for d in diagnoses))
        recall = top3 / total if total else 0.0
        table.append(
            {
                "mode": mode,
                "count": total,
                "L1 Acc": round(l1 / total, 4),
                "L2 Acc": round(l2 / total, 4),
                "L3 Acc": round(l3 / total, 4),
                "Top-3 Acc": round(top3 / total, 4),
                "Recall": round(recall, 4),
            }
        )
    return table


def save_table(table: List[Dict[str, Any]], output: str) -> None:
    if not table:
        return
    os.makedirs(os.path.dirname(output) or ".", exist_ok=True)
    with open(output, "w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(table[0].keys()))
        writer.writeheader()
        writer.writerows(table)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate B0/B1/B2 comparison metrics.")
    parser.add_argument("--inputs", nargs="+", default=["./storage/results/*.json"], help="Result JSON/CSV files or globs.")
    parser.add_argument("--output", default="./storage/results/metrics_comparison.csv")
    args = parser.parse_args()

    rows = load_results(args.inputs)
    if not rows:
        print("[WARN] 没有找到 baseline 结果。请先运行 B0/B1，例如：")
        print("  python baselines/run_b0_direct.py --text \"ALT 85 U/L\" --mock")
        print("  python baselines/run_b1_rag.py --text \"ALT 85 U/L\" --mock")
        return 0
    table = compute_metrics(rows)
    save_table(table, args.output)
    print(json.dumps(table, ensure_ascii=False, indent=2))
    print(f"[INFO] Metrics saved to: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
